version: "3.8"

services:
  # Backend Spring Boot Service
  be-moongsan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-moongsan
    ports:
      - "8080:8080"
    networks:
      - moongsan-net
    depends_on:
      - redis-moongsan
      - mongo-moongsan
    restart: unless-stopped
    volumes:
      - /var/moongsan/log:/app/logs

  # Redis Cache Service
  redis-moongsan:
    image: redis:7.2-alpine
    container_name: redis-moongsan
    ports:
      - "6379:6379"
    networks:
      - moongsan-net
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  # MongoDB Service
  mongo-moongsan:
    image: mongo:6.0.7
    container_name: mongo-moongsan
    ports:
      - "27017:27017"
    networks:
      - moongsan-net
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

networks:
  moongsan-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  redis-data:
    driver: local
  mongo-data:
    driver: local
