# application-secrets.yml

# DB
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
  data:
    mongodb:
      database: ${MONGO_DB}
      uri: ${MONGO_DB_URI}

# S3
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

# AI
ai:
  service:
    base-url: ${AI_SERVICE_BASE_URL}

# jwt
jwt:
  secret: your-very-secure-secret-key-must-be-long-enough
  access-token-expire-ms: 3600000
  refresh-token-expire-ms: 1209600000
