# application-secrets.yml

# DB
DB_URL: ${DB_URL}
DB_USERNAME: ${DB_USERNAME}
DB_PASSWORD: ${DB_PASSWORD}
DB_DRIVER: ${DB_DRIVER}

# S3
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

# AI
ai:
  service:
    base-url: ${AI_SERVICE_BASE_URL}


